---
AllCops:
  TargetRubyVersion: 2.7.5
  Exclude:
    - test/dummy/**/*
  NewCops: disable

Layout/LineLength:
  Exclude:
  - test/dummy/**/*
  Max: 100
  IgnoredPatterns: ['\A#', ' # ']

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

